# The URL the site will be built for
base_url = "https://philhansch.net/"

title = "Philipp Hansch"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true


# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author.name = "Philipp Hansch"
author.email = "hi@philhansch.net"
author.twitter = "philhansch"
author.patreon = "philhansch"
author.github = "phansch"
author.about = "Philipp is a full stack developer <s>currently heavily involved with Rust. Most notably he's a member of the Clippy team where he helps with bugfixing and documentation.</s> You can follow him on <a href='https://mastodon.social/@phansch'>Mastodon</a> and find him on <a href='https://github.com/{{ config.extra.author.github }}'>GitHub</a> as well as <a href='https://patreon.com/{{ config.extra.author.patreon }}'>Patreon</a>."
